require("dotenv").config();

module.exports = {
  PORT: process.env.PORT || 3030,
  DB_URL: process.env.DB_URL,
  DB_USERNAME: process.env.DB_USERNAME,
  DB_PASSWORD: process.env.DB_PASSWORD,
  JWT_ACCESS_SECRET_KEY: process.env.JWT_ACCESS_SECRET_KEY,
  JWT_REFRESH_SECRET_KEY: process.env.JWT_REFRESH_SECRET_KEY,
  JWT_RESET_PASSWORD_SECRET_KEY: process.env.JWT_RESET_PASSWORD_SECRET_KEY,
  JWT_VERIFY_EMAIL_SECRET_KEY: process.env.JWT_VERIFY_EMAIL_SECRET_KEY,
  JWT_EMAIL_VERIFICATION_EXPIRATION: process.env.JWT_EMAIL_VERIFICATION_EXPIRATION || "1d",
  JWT_RESET_PASSWORD_EXPIRATION: process.env.JWT_RESET_PASSWORD_EXPIRATION    || "1h",
  JWT_ACCESS_TOKEN_EXPIRATION: process.env.JWT_ACCESS_TOKEN_EXPIRATION || "15m",
  JWT_REFRESH_TOKEN_EXPIRATION: process.env.JWT_REFRESH_TOKEN_EXPIRATION || "7d",
  JWT_RESET_PASSWORD_URL: process.env.JWT_RESET_PASSWORD_URL || "http://localhost:3030/api/auth/reset-password",
  JWT_VERIFY_EMAIL_URL: process.env.JWT_VERIFY_EMAIL_URL,
  JWT_SECRET: process.env.JWT_SECRET_KEY                                                       
};